version: "3.8"
  services:
    app:
      build:
        context: .
        target: builder
      volumes:
        - .:/app
      ports:
        - "3000:3000"
      environment:
        - NODE_ENV=development
      command: yarn run dev
      restart: unless-stopped
