version: "3.8"
  services:
    app:
      build:
        context: .
        target: production
      volumes:
        - .:/app
      ports:
        - "3000:3000"
      environment:
        - NODE_ENV=production
      restart: unless-stopped
